# Generated by Django 2.0.6 on 2019-02-27 21:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=400)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 2, 27, 21, 32, 14, 379168, tzinfo=utc))),
                ('published_date', models.DateTimeField(default=datetime.datetime(2019, 2, 27, 21, 32, 14, 379192, tzinfo=utc))),
            ],
        ),
    ]
